#!/bin/sh

set -e

lb config noauto \
	--architectures amd64 \
	--archive-areas "main" \
	--distribution buster \
	--apt-recommends false \
	--apt-indices false \
	--debootstrap-options "--variant=minbase" \
	--memtest none \
	--iso-application Spearmint Live \
	--iso-preparer Grant Handy \
	--iso-publisher Spearmint OS Project \
	"${@}"
