#!/bin/sh

set -e

lb config noauto \
	--architectures amd64 \
	--mirror-bootstrap http://mirrors.xmission.com/debian/ \
	--mirror-binary http://mirrors.xmission.com/debian/ \
	--archive-areas "main" \
	--distribution buster \
	--apt-recommends false \
	--debootstrap-options "--variant=minbase" \
	--memtest none \
	"${@}"
